exec-once = [workspace 1 silent] kitty
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 3 silent] obsidian
exec-once = [workspace special silent] discord

exec-once=systemctl --user start plasma-polkit-agent
