windowrulev2 = suppressevent maximize, class:.*

windowrulev2 = size 75% 75%, floating:1
windowrulev2 = center, floating:1

# Discord - Special workspace, floating
windowrulev2 = workspace special:discord, class:(discord)
windowrulev2 = float, class:(discord)
windowrulev2 = stayfocused, class:(discord)
windowrulev2 = size 75% 75%, class:(discord)
windowrulev2 = center, class:(discord)

# Betterbird - Special workspace, maximised
windowrulev2 = workspace special:mail, class:(betterbird)
windowrulev2 = stayfocused, class:(betterbird)
windowrulev2 = fullscreen, class:(betterbird)
windowrulev2 = fullscreenstate:1, class:(betterbird)

# Pavucontrol - Floating
windowrulev2 = float, class:(org.pulseaudio.pavucontrol)
windowrulev2 = stayfocused, class:(org.pulseaudio.pavucontrol)
windowrulev2 = size 75% 75%, class:(org.pulseaudio.pavucontrol)
windowrulev2 = center, class:(org.pulseaudio.pavucontrol)

# Blueman Manager - Floating
windowrulev2 = float, class:(blueman-manager-wrapped)
windowrulev2 = stayfocused, class:(blueman-manager-wrapped)
windowrulev2 = size 75% 75%, class:(blueman-manager-wrapped)
windowrulev2 = center, class:(blueman-manager-wrapped)

