{ lib, ... }: {
  # Auto-generated by nixos-infect!

  networking = {
    nameservers = [ "8.8.8.8"
 ];
    defaultGateway = "172.31.1.1";
    defaultGateway6 = {
      address = "fe80::1";
      interface = "eth0";
    };
    dhcpcd.enable = false;
    usePredictableInterfaceNames = lib.mkForce false;
    interfaces = {
      eth0 = {
        ipv4.addresses = [
          { address="116.203.50.47"; prefixLength=32; }
        ];
        ipv6.addresses = [
          { address="2a01:4f8:1c1a:3394::1"; prefixLength=64; }
{ address="fe80::9000:6ff:fee7:1bf5"; prefixLength=64; }
        ];
        ipv4.routes = [ { address = "172.31.1.1"; prefixLength = 32; } ];
        ipv6.routes = [ { address = "fe80::1"; prefixLength = 128; } ];
      };

    };
  };
  services.udev.extraRules = ''
    ATTR{address}=="92:00:06:e7:1b:f5", NAME="eth0"

  '';
}
